server:
  port: 8060
spring:
  application:
    name: hystrix
#eureka 配置
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
#开启feign
feign:
  hystrix:
    enabled: true
 #数据监控
management:
  endpoints:
    web:
      exposure:
        include: 'hystrix.stream'